/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VermietungRouteImport } from './routes/vermietung'
import { Route as StandorteRouteImport } from './routes/standorte'
import { Route as KurseRouteImport } from './routes/kurse'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const VermietungRoute = VermietungRouteImport.update({
  id: '/vermietung',
  path: '/vermietung',
  getParentRoute: () => rootRouteImport,
} as any)
const StandorteRoute = StandorteRouteImport.update({
  id: '/standorte',
  path: '/standorte',
  getParentRoute: () => rootRouteImport,
} as any)
const KurseRoute = KurseRouteImport.update({
  id: '/kurse',
  path: '/kurse',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRoute
  '/standorte': typeof StandorteRoute
  '/vermietung': typeof VermietungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRoute
  '/standorte': typeof StandorteRoute
  '/vermietung': typeof VermietungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRoute
  '/standorte': typeof StandorteRoute
  '/vermietung': typeof VermietungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/kurse' | '/standorte' | '/vermietung'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/kurse' | '/standorte' | '/vermietung'
  id: '__root__' | '/' | '/kontakt' | '/kurse' | '/standorte' | '/vermietung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  KurseRoute: typeof KurseRoute
  StandorteRoute: typeof StandorteRoute
  VermietungRoute: typeof VermietungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vermietung': {
      id: '/vermietung'
      path: '/vermietung'
      fullPath: '/vermietung'
      preLoaderRoute: typeof VermietungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standorte': {
      id: '/standorte'
      path: '/standorte'
      fullPath: '/standorte'
      preLoaderRoute: typeof StandorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurse': {
      id: '/kurse'
      path: '/kurse'
      fullPath: '/kurse'
      preLoaderRoute: typeof KurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  KurseRoute: KurseRoute,
  StandorteRoute: StandorteRoute,
  VermietungRoute: VermietungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
