/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VermietungRouteImport } from './routes/vermietung'
import { Route as StandorteRouteImport } from './routes/standorte'
import { Route as KurseRouteImport } from './routes/kurse'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KurseIndexRouteImport } from './routes/kurse.index'
import { Route as KurseSlugRouteImport } from './routes/kurse.$slug'

const VermietungRoute = VermietungRouteImport.update({
  id: '/vermietung',
  path: '/vermietung',
  getParentRoute: () => rootRouteImport,
} as any)
const StandorteRoute = StandorteRouteImport.update({
  id: '/standorte',
  path: '/standorte',
  getParentRoute: () => rootRouteImport,
} as any)
const KurseRoute = KurseRouteImport.update({
  id: '/kurse',
  path: '/kurse',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KurseIndexRoute = KurseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KurseRoute,
} as any)
const KurseSlugRoute = KurseSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KurseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRouteWithChildren
  '/standorte': typeof StandorteRoute
  '/vermietung': typeof VermietungRoute
  '/kurse/$slug': typeof KurseSlugRoute
  '/kurse/': typeof KurseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/standorte': typeof StandorteRoute
  '/vermietung': typeof VermietungRoute
  '/kurse/$slug': typeof KurseSlugRoute
  '/kurse': typeof KurseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/kurse': typeof KurseRouteWithChildren
  '/standorte': typeof StandorteRoute
  '/vermietung': typeof VermietungRoute
  '/kurse/$slug': typeof KurseSlugRoute
  '/kurse/': typeof KurseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/kurse'
    | '/standorte'
    | '/vermietung'
    | '/kurse/$slug'
    | '/kurse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/standorte'
    | '/vermietung'
    | '/kurse/$slug'
    | '/kurse'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/kurse'
    | '/standorte'
    | '/vermietung'
    | '/kurse/$slug'
    | '/kurse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  KurseRoute: typeof KurseRouteWithChildren
  StandorteRoute: typeof StandorteRoute
  VermietungRoute: typeof VermietungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vermietung': {
      id: '/vermietung'
      path: '/vermietung'
      fullPath: '/vermietung'
      preLoaderRoute: typeof VermietungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standorte': {
      id: '/standorte'
      path: '/standorte'
      fullPath: '/standorte'
      preLoaderRoute: typeof StandorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurse': {
      id: '/kurse'
      path: '/kurse'
      fullPath: '/kurse'
      preLoaderRoute: typeof KurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurse/': {
      id: '/kurse/'
      path: '/'
      fullPath: '/kurse/'
      preLoaderRoute: typeof KurseIndexRouteImport
      parentRoute: typeof KurseRoute
    }
    '/kurse/$slug': {
      id: '/kurse/$slug'
      path: '/$slug'
      fullPath: '/kurse/$slug'
      preLoaderRoute: typeof KurseSlugRouteImport
      parentRoute: typeof KurseRoute
    }
  }
}

interface KurseRouteChildren {
  KurseSlugRoute: typeof KurseSlugRoute
  KurseIndexRoute: typeof KurseIndexRoute
}

const KurseRouteChildren: KurseRouteChildren = {
  KurseSlugRoute: KurseSlugRoute,
  KurseIndexRoute: KurseIndexRoute,
}

const KurseRouteWithChildren = KurseRoute._addFileChildren(KurseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  KurseRoute: KurseRouteWithChildren,
  StandorteRoute: StandorteRoute,
  VermietungRoute: VermietungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
